DMarray:main.c DynamicArray.c ../Mysort/Mysort.c
	gcc main.c DynamicArray.c ../Mysort/Mysort.c -o DMarray

# DMarray:main1.c DynamicArray1.c ../Mysort/Mysort.c
# 	gcc main1.c DynamicArray1.c ../Mysort/Mysort.c -o DMarray