LQmain: Queue.c LQmain.c DoubleLinkList.c
	gcc Queue.c LQmain.c DoubleLinkList.c -o LQmain
# LSmain: LinkStack.c LSmain.c DoubleLinkList.c
# 	gcc LinkStack.c LSmain.c DoubleLinkList.c -o LSmain

# DCLmain: DoubleCircleLinkList.c DCLmain.c
# 	gcc DoubleCircleLinkList.c DCLmain.c -o DCLmain

# main:DoubleLinkList.c main.c
# 	gcc DoubleLinkList.c main.c -o main