# MagicTower: MagicTower.c DynamicArray.c Mysort.c MyString.c Interface.c Role.c Tools.c
# 	gcc MagicTower.c DynamicArray.c Mysort.c MyString.c Interface.c Role.c -o Tools.c MagicTower

# .PHONY:clean

# clean: 
# 	rm -f MagicTower

OBJECTS=*.c
MagicTower:${OBJECTS}
	gcc ${OBJECTS} -o MagicTower

.PHONY:clean

clean: 
	rm -f MagicTower