# main:../0802/DoubleLinkList.c ../0802/LinkStack.c ../0802/LQueue.c main.c
# 	gcc ../0802/DoubleLinkList.c ../0802/LinkStack.c ../0802/LQueue.c main.c -o main

OBJECTS=DoubleLinkList.c LinkStack.c LQueue.c main.c LQueue.c
main:${OBJECTS}
	gcc ${OBJECTS} -o main

.PHONY:clean

clean:
	rm -f main
