MagicTower:MagicTower.c DynamicArray.c MyString.c main.c StdFile.c DoubleLinkList.c LoginSignup.c
	gcc MagicTower.c DynamicArray.c MyString.c main.c StdFile.c DoubleLinkList.c LoginSignup.c -o MagicTower
.PHONY:clean

clean:
	rm -f MagicTower