MagicTower: MagicTower.c ../MyLibrary/DynamicArray/DynamicArray.c ../MyLibrary/Mysort/Mysort.c ../MyLibrary/MyString/MyString.c
	gcc MagicTower.c ../MyLibrary/DynamicArray/DynamicArray.c ../MyLibrary/Mysort/Mysort.c ../MyLibrary/MyString/MyString.c -o MagicTower

.PHONY:clean

clean: 
	rm -f MagicTower